package telemetry

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	sdktrace "go.opentelemetry.io/otel/sdk/trace"

	"djinni-bot-go/internal/logger"
)

// ADKSpanProcessor implements sdktrace.SpanProcessor to intercept
// OpenTelemetry spans generated by ADK and route them to our deep logger.
type ADKSpanProcessor struct{}

func NewADKSpanProcessor() sdktrace.SpanProcessor {
	return &ADKSpanProcessor{}
}

func (p *ADKSpanProcessor) OnStart(parent context.Context, s sdktrace.ReadWriteSpan) {}

func (p *ADKSpanProcessor) OnEnd(s sdktrace.ReadOnlySpan) {
	stage := s.Name()
	
	attrs := make(map[string]any)
	for _, kv := range s.Attributes() {
		attrs[string(kv.Key)] = maskSensitive(string(kv.Key), kv.Value.AsInterface())
	}
	
	events := make([]map[string]any, 0, len(s.Events()))
	for _, ev := range s.Events() {
		evAttrs := make(map[string]any)
		for _, kv := range ev.Attributes {
			evAttrs[string(kv.Key)] = maskSensitive(string(kv.Key), kv.Value.AsInterface())
		}
		events = append(events, map[string]any{
			"name":       ev.Name,
			"attributes": evAttrs,
		})
	}

	attrBytes, _ := json.Marshal(attrs)
	eventBytes, _ := json.Marshal(events)

	msg := fmt.Sprintf("Status: %s | Attributes: %s | Events: %s", 
		s.Status().Code.String(), string(attrBytes), string(eventBytes))

	logger.LogDeep(stage, msg)
}

func (p *ADKSpanProcessor) Shutdown(ctx context.Context) error {
	return nil
}

func (p *ADKSpanProcessor) ForceFlush(ctx context.Context) error {
	return nil
}

func maskSensitive(key string, val any) any {
	lowerKey := strings.ToLower(key)
	if strings.Contains(lowerKey, "key") || 
	   strings.Contains(lowerKey, "token") || 
	   strings.Contains(lowerKey, "password") || 
	   strings.Contains(lowerKey, "secret") || 
	   strings.Contains(lowerKey, "session") || 
	   strings.Contains(lowerKey, "auth") {
		return "***MASKED***"
	}
	return val
}
